name = "PyroLeanExamples"
version = "0.1.0"
defaultTargets = ["pyroleanexamples"]

[[lean_lib]]
name = "PyroLeanExamples"

[[lean_exe]]
name = "pyroleanexamples"
root = "Main"

[[require]]
name = "aesop"
scope = "leanprover-community"
git = "https://github.com/leanprover-community/aesop"
rev = "master"

[[require]]
name = "LeanALaCarte"
scope = "arthur-adjedj"
git = "https://github.com/arthur-adjedj/LeanALaCarte"
rev = "main"

[[require]]
name = "mathlib"
scope = "leanprover-community"